files: "^content/"

repos:
  - repo: local
    hooks:
      - id: unordered-list
        name: lists are preceded by empty line
        files: "\\.md$"
        language: pygrep
        entry: "^(?! ?-)(?-s:.+)\n ?-(?!-)"
        args: [--multiline]
      - id: markdown-ordered-list
        name: numbered lists are preceded by empty line
        files: "\\.md$"
        language: pygrep
        entry: "^(?-s:.+)\n ?1\\."
        args: [ --multiline ]
