files: "^content/"

repos:
  - repo: local
    hooks:
      - id: markdown-check-list
        name: check that lists are preceded by empty line
        files: "\\.md$"
        language: pygrep
        entry: "^(?! ?-)(?-s:.+)\n ?-(?!-)"
        args: [--multiline]
