# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Laszlo Treszkai
email: laszlo.treszkai@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
#  Explorations in math, AI, ML.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ltreszkai
github_username:  treszkai
permalink: /:year-:month-:day-:title

# Google Analytics
# google_analytics: UA-114915944-1

# Build settings
markdown: kramdown
kramdown:
 math_engine: nil
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

minima:
  date_format: "%-d %b. %Y"

scholar:
  sort_by: author, year, month, title

latex_macros:
    \RR: \mathbb{R}
    \EE: \mathbb{E}
    \parm: \color{grey}{\bullet}
    \indep: \perp\!\!\!\perp
    \emptyset: \varnothing
    \proves: \vdash
    \Union: \bigcup
    \Intersect: \bigcap
    \grad: \nabla

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
